# Generated by Django 4.0.2 on 2022-06-10 17:12

from django.db import migrations, models
import erp_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vat_id', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('industry', models.CharField(choices=[('ENERGY', 'Energy'), ('RETAIL', 'Retail'), ('TECH', 'Tech'), ('OTHER', 'Other')], default=erp_core.models.Company.Industry['TECH'], max_length=15)),
            ],
        ),
    ]
