# Generated by Django 4.0.2 on 2022-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
