# Generated by Django 4.0.2 on 2022-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0003_company_address_company_city_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
