# Generated by Django 4.0.2 on 2022-06-13 10:10

from django.db import migrations, models
import django.db.models.deletion
import erp_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0004_alter_company_address_alter_company_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kind', models.CharField(choices=[('ACTIVE', 'Active'), ('PASSIVE', 'Passive'), ('CREDIT', 'Credit Note')], max_length=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default=erp_core.models.Invoice.Status['UNPAID'], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receiver', to='erp_core.company')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sender', to='erp_core.company')),
            ],
        ),
    ]
