# Generated by Django 4.0.2 on 2022-06-15 13:32

from django.db import migrations, models
import erp_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('ENERGY', 'Energy'), ('RETAIL', 'Retail'), ('TECH', 'Tech'), ('OTHER', 'Other')], default=erp_core.models.Company.Industry['ENERGY'], max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PASSIVE', 'Passive'), ('CREDIT', 'Credit Note')], default=0, max_length=10),
        ),
    ]
