# Generated by Django 4.0.2 on 2022-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0006_alter_company_industry_alter_invoice_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default=1, max_length=10),
        ),
    ]
