# Generated by Django 4.0.2 on 2022-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0007_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('ENERGY', 'Energy'), ('RETAIL', 'Retail'), ('TECH', 'Tech'), ('OTHER', 'Other')], default='ENERGY', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PASSIVE', 'Passive'), ('CREDIT', 'Credit Note')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=10),
        ),
    ]
