# Generated by Django 4.0.2 on 2022-06-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0008_alter_company_industry_alter_invoice_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['date']},
        ),
    ]
